CREATE TABLE employees
(
    id              uuid    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1),
    name            varchar NOT NULL,
    surname         varchar NOT NULL,
    phone           varchar NOT NULL,
    company_id      varchar NOT NULL,
    passport_type   varchar NOT NULL,
    passport_number varchar NOT NULL,
    department_id   varchar NOT NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (id) /* устанавливаем ограничение на столбец id,
                                                   это первичный ключ который будет уникальным*/


);

CREATE TABLE department
(
    id          uuid    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1),
    name        varchar NOT NULL,
    phone       varchar NOT NULL,
    employee_id varchar NOT NULL,
    CONSTRAINT department_pkey PRIMARY KEY (id),
    CONSTRAINT department_01t_fkey FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT ON UPDATE RESTRICT
    /*внешний ключ(employee_id) ссылается на столбец
      id  в "родительской" таблице + добавлем ограничение,
      что значения внешнего ключа будут ссылаться только на
      существующие значения в стбце id в родительской таблице*/
);









